type DeviceInfo = {
  userAgent: string;
  platform?: string;
  maxTouchPoints?: number;
  userAgentData?: { platform: string; mobile: boolean };
};

const DEVICE_KEY = "lan-drop-device-id";
const NAME_KEY = "lan-drop-device-name";
const VERSION_KEY = "lan-drop-device-name-version";
const MODE_KEY = "lan-drop-device-name-mode";
const VERSION = "device-info-v1";

// Only used to migrate names generated by the previous release.
const LEGACY_NAME = /^(会飞的|倒立的|发光的|迷路的|会唱歌的|隐形的|熬夜的|跳舞的|生气的|爱摸鱼的|打嗝的|戴墨镜的)(西瓜|章鱼|土豆|拖鞋|企鹅|海豹|蘑菇|鲨鱼|月亮|煎饼|胡萝卜|小笼包|仙人掌|河马|云朵)$/;

export function getDeviceName(info: DeviceInfo): string {
  const ua = info.userAgent;
  const platform = info.userAgentData?.platform || info.platform || "";
  if (/iPad/i.test(ua) || (/Mac/i.test(platform + ua) && (info.maxTouchPoints ?? 0) > 1)) return "iPad";
  if (/iPhone/i.test(ua)) return "iPhone";
  if (/iPod/i.test(ua)) return "iPod";
  if (/Android/i.test(platform + ua)) {
    const model = ua.match(/Android[^;)]*;\s*(?:[a-z]{2}[-_][a-z]{2};\s*)?([^;)]+)/i)?.[1]
      ?.replace(/\s+Build\/.*$/i, "").trim();
    // Reduced Android user agents use "K" instead of a real model.
    if (model && !/^(K|wv|Mobile|Tablet|Linux|[a-z]{2}[-_][a-z]{2})$/i.test(model)) return model.slice(0, 32);
    return (info.userAgentData?.mobile ?? /Mobile/i.test(ua)) ? "Android 手机" : "Android 平板";
  }
  if (/Windows|Win32|Win64/i.test(platform + ua)) return "Windows 电脑";
  if (/CrOS|Chrome OS/i.test(platform + ua)) return "Chromebook";
  if (/Mac/i.test(platform + ua)) return "Mac 电脑";
  if (/Linux/i.test(platform + ua)) return "Linux 电脑";
  return /Mobile/i.test(ua) ? "移动设备" : "未知设备";
}

export function readIdentity(storage: Storage, info: DeviceInfo, createId: () => string) {
  const deviceId = storage.getItem(DEVICE_KEY) || createId();
  storage.setItem(DEVICE_KEY, deviceId);
  const savedName = storage.getItem(NAME_KEY)?.trim();
  const version = storage.getItem(VERSION_KEY);
  const custom = version === VERSION
    ? storage.getItem(MODE_KEY) === "custom"
    : Boolean(savedName && !LEGACY_NAME.test(savedName));
  const name = custom && savedName ? savedName.slice(0, 32) : getDeviceName(info);
  storage.setItem(NAME_KEY, name);
  storage.setItem(VERSION_KEY, VERSION);
  storage.setItem(MODE_KEY, custom && savedName ? "custom" : "auto");
  return { deviceId, name };
}

export function saveDeviceName(storage: Storage, input: string, info: DeviceInfo) {
  const customName = input.trim().slice(0, 32);
  const name = customName || getDeviceName(info);
  storage.setItem(NAME_KEY, name);
  storage.setItem(VERSION_KEY, VERSION);
  storage.setItem(MODE_KEY, customName ? "custom" : "auto");
  return name;
}
